#!/usr/bin/env python3

import hashlib

def hash(data: bytes) -> bytes:
    return hashlib.md5(data).digest()

# Set up data
x0 = bytes.fromhex(''.join('00' for i in range(16)))
x1 = bytes.fromhex(''.join('01' for i in range(16)))
x2 = bytes.fromhex(''.join('02' for i in range(16)))
x3 = bytes.fromhex(''.join('03' for i in range(16)))
x4 = bytes.fromhex(''.join('04' for i in range(16)))
x5 = bytes.fromhex(''.join('05' for i in range(16)))
x6 = bytes.fromhex(''.join('06' for i in range(16)))
x7 = bytes.fromhex(''.join('07' for i in range(16)))

# Make hashes
y0 = hash(x0)
y1 = hash(x1)
y2 = hash(x2)
y3 = hash(x3)
y4 = hash(x4)
y5 = hash(x5)
y6 = hash(x6)
y7 = hash(x7)

y8  = hash(y0  + y1 )
y9  = hash(y2  + y3 )
y10 = hash(y4  + y5 )
y11 = hash(y6  + y7 )

y12 = hash(y8  + y9 )
y13 = hash(y10 + y11)

y14 = hash(y12 + y13)

print("3-Layer MD5 Merkle Tree")
print("#"*72)
print()
print("Data")
print()
print('x0 = %s' % (x0.hex()))
print('x1 = %s' % (x1.hex()))
print('x2 = %s' % (x2.hex()))
print('x3 = %s' % (x3.hex()))
print('x4 = %s' % (x4.hex()))
print('x5 = %s' % (x5.hex()))
print('x6 = %s' % (x6.hex()))
print('x7 = %s' % (x7.hex()))
print()
print()

print("Merkle Tree")
print()
print('y0  = md5(x0)')
print('    = %s' % (y0.hex()))
print('y1  = md5(x1)')
print('    = %s' % (y1.hex()))
print('y2  = md5(x2)')
print('    = %s' % (y2.hex()))
print('y3  = md5(x3)')
print('    = %s' % (y3.hex()))
print('y4  = md5(x4)')
print('    = %s' % (y4.hex()))
print('y5  = md5(x5)')
print('    = %s' % (y5.hex()))
print('y6  = md5(x6)')
print('    = %s' % (y6.hex()))
print('y7  = md5(x7)')
print('    = %s' % (y7.hex()))
print()

print('y8  = md5(y0 ||y1 )')
print('    = %s' % (y8.hex()))
print('y9  = md5(y2 ||y3 )')
print('    = %s' % (y9.hex()))
print('y10 = md5(y4 ||y5 )')
print('    = %s' % (y10.hex()))
print('y11 = md5(y6 ||y7 )')
print('    = %s' % (y11.hex()))
print()

print('y12 = md5(y8 ||y9 )')
print('    = %s' % (y12.hex()))
print('y13 = md5(y10||y11)')
print('    = %s' % (y13.hex()))
print()

print('y14 = md5(y12||y13)')
print('    = %s' % (y14.hex()))
